jaffle_shop: # this needs to match the profile: in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /Users/laura.vilaseca/jaffle_shop/dbt-user-creds.json # replace this with the full path to your keyfile
      project: stoked-brand-343809 # Replace this with your project id
      dataset: dbt_laura # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive

      https://github:
        com/USERNAME/dbt-tutorial:
          git: